# One Dark Theme for Kitty
# Based on the Atom One Dark theme

foreground            #abb2bf
background            #282c34
selection_foreground  #abb2bf
selection_background  #3e4451

color0   #282c34
color8   #545862

color1   #e06c75
color9   #e06c75

color2   #98c379
color10  #98c379

color3   #e5c07b
color11  #e5c07b

color4   #61afef
color12  #61afef

color5   #c678dd
color13  #c678dd

color6   #56b6c2
color14  #56b6c2

color7   #abb2bf
color15  #c8ccd4

# Cursor colors
cursor            #528bff
cursor_text_color #282c34

# URL underline color when hovering with mouse
url_color #61afef

# Tab bar colors
active_tab_foreground   #abb2bf
active_tab_background   #282c34
inactive_tab_foreground #565c64
inactive_tab_background #21252b
tab_bar_background      #21252b

# The color for the border of the active window
active_border_color #528bff

# The color for the border of inactive windows
inactive_border_color #3e4451
